#!/bin/sh

git diff --cached --name-status | while read file; do        
        if [[ "$file" =~ "config" ]]; then
                echo "$file cannot be changed. Retry after reverting changes!"
                exit 1
        fi
done